import type { Metadata } from "next";
import { ThemeProvider } from "next-themes";
import "./globals.css";

export const metadata: Metadata = {
	title: "Simple ToDo",
	description: "Generated by create next app",
	keywords: "todo",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en" suppressHydrationWarning>
			<body>
				<ThemeProvider
					attribute="class"
					defaultTheme="light"
					themes={["light", "dark"]}
					enableSystem={false}>
					{children}
				</ThemeProvider>
			</body>
		</html>
	);
}
